"""Canonical domain models for the control plane."""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

SCHEMA_VERSION = "v1"


class TicketPriority(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class TicketStatus(StrEnum):
    READY = "ready"
    CLAIMED = "claimed"
    COMPLETED = "completed"
    FAILED = "failed"


class RunState(StrEnum):
    CLAIMED = "claimed"
    RUNNING = "running"
    BLOCKED = "blocked"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    TIMED_OUT = "timed_out"
    CANCELED = "canceled"
    AWAITING_APPROVAL = "awaiting_approval"


class ArtifactType(StrEnum):
    LOG = "log"
    PATCH = "patch"
    TEST_REPORT = "test_report"
    POLICY_REPORT = "policy_report"
    OTHER = "other"


class Ticket(BaseModel):
    """Backlog ticket normalized across sources."""

    model_config = ConfigDict(extra="forbid")

    schema_version: str = SCHEMA_VERSION
    id: str = Field(default_factory=lambda: str(uuid4()))
    source: str
    type: str
    priority: TicketPriority = TicketPriority.MEDIUM
    repo: str
    context: dict[str, Any] = Field(default_factory=dict)
    acceptance_criteria: list[str] = Field(default_factory=list)
    idempotency_key: str
    status: TicketStatus = TicketStatus.READY
    attempts: int = 0
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class Lease(BaseModel):
    """Ownership lease for a claimed ticket."""

    model_config = ConfigDict(extra="forbid")

    ticket_id: str
    owner: str
    token: str
    expires_at: datetime
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class RunBudget(BaseModel):
    """Limits enforced by the run supervisor."""

    model_config = ConfigDict(extra="forbid")

    max_minutes: int
    max_tokens: int


class Run(BaseModel):
    """Execution attempt for a ticket."""

    model_config = ConfigDict(extra="forbid")

    schema_version: str = SCHEMA_VERSION
    run_id: str = Field(default_factory=lambda: str(uuid4()))
    ticket_id: str
    harness: str
    state: RunState = RunState.CLAIMED
    sandbox_id: str | None = None
    lease_token: str
    budget: RunBudget
    token_count: int = 0
    started_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    heartbeat_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    ended_at: datetime | None = None
    error_message: str | None = None


class Artifact(BaseModel):
    """Artifact generated by a run."""

    model_config = ConfigDict(extra="forbid")

    schema_version: str = SCHEMA_VERSION
    id: str = Field(default_factory=lambda: str(uuid4()))
    run_id: str
    ticket_id: str
    type: ArtifactType
    uri: str
    metadata: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class PolicyCheck(BaseModel):
    """Single governance policy check result."""

    model_config = ConfigDict(extra="forbid")

    rule_id: str
    passed: bool
    summary: str
    evidence_uri: str | None = None


class PolicyReport(BaseModel):
    """Consolidated governance result for a PR/run."""

    model_config = ConfigDict(extra="forbid")

    schema_version: str = SCHEMA_VERSION
    id: str = Field(default_factory=lambda: str(uuid4()))
    run_id: str
    ticket_id: str
    passed: bool
    checks: list[PolicyCheck]
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


SCHEMA_MODEL_REGISTRY: dict[str, type[BaseModel]] = {
    "ticket": Ticket,
    "run": Run,
    "lease": Lease,
    "artifact": Artifact,
    "policy_report": PolicyReport,
}
